config/routes.rb
Pollster::Application.routes.draw do
  root to: 'polls#index'
  resources :polls do
    resources :answers, only: [:create, :destroy]
  end

  match ':encrypted_link' => 'polls#show'

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :poll
  validates :body, :presence => true, :length => { :maximum => 250 }
  validates_associated :poll
  attr_accessible :body
end

app/models/poll.rb
class Poll < ActiveRecord::Base
  attr_accessible :question, :encrypted_link, :title
 	has_many :answers
 	validates_presence_of :title, :question
 	before_create :encrypt_link

  def format_url
  	(('a'..'z').to_a + ('1'..'9').to_a + ('A'..'Z').to_a).shuffle[0..5].join
  end

  def encrypt_link
  	self.encrypted_link = format_url
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		@poll = Poll.find(params[:poll_id])
		@answer = @poll.answers.build(params[:answer])
		if @answer.save
			redirect_to root_url, :notice => "Thank you for your answer!"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polls_controller.rb
class PollsController < ApplicationController

	def index
		@poll = Poll.new
		@polls = Poll.all
	end

	def create
		@poll = Poll.new(params[:poll])
		if @poll.save
			redirect_to @poll, notice: 'Poll was successfully created.' 
		else
			flash[:error] = "Something went wrong!"
			render 'new'
		end
	end

	def edit
		@poll = Poll.find(params[:id])
	end

	def update
		@poll = Poll.find(params[:id])
		if @poll.update_attributes(params[:poll])
			redirect_to @poll, notice: 'Poll was successfully updated.' 
		else
			flash[:error] = "Something went wrong!"
			render :action => :edit
		end
	end

	def show
		@poll = Poll.find(params[:id])
		#@poll = Poll.includes(:answers).find_by_encrypted_link(params[:encrypted_link])
	end

	def destroy
		@poll = Poll.find(params[:id])
		@poll.destroy
		redirect_to :root, notice: 'Poll was successfully deleted.' 		
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polls_helper.rb
module PollsHelper
end

app/views/answers/_answer.html.erb
<div class="answer">
  <%= raw answer.body %> 
    <%= link_to 'Destroy', poll_answer_path(answer.poll, answer), method: :delete, data: { confirm: 'Are you sure?' } %>
</div>

app/views/answers/_form.html.erb
<div class="form_for">
	<%= form_for [@poll, @answer = Answer.new] do |f| %>
<div>
  <%= f.text_area :body, rows: 2 %>
</div>
<div>
  <%= f.submit 'Answer' %>
</div>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pollifier</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="header"><h1><%= link_to 'Pollifier', root_url %></h1></div><!/header>
		<div class="wrapper">
			<div class="container">
				<p id="notice"><%= flash[:notice] %></p>
				<%= yield %>
				<%#= debug params %>
			</div><!/container>
		</div><!/wrapper>
	<div class="footer">
		
			<p><%= Time.now.year %> &copy; <%= link_to 'Home', root_url %></p>
			
	</div>
</body>
</html>

app/views/polls/_form.html.erb
<div class="form_for">
	<%= form_for(@poll) do |f| %>
		<%= f.text_field :title, :placeholder => 'What will your poll be called?' %><br/>
		<%= f.text_area :question, :placeholder => 'What do you want to ask?' %><br/>
		<%= f.submit 'Create Poll' %>
	<% end %>
</div>

app/views/polls/edit.html.erb
<h2>Edit Poll</h2>

<%= render 'form' %>

<%= link_to 'Show', @poll %><br/>
<%= link_to 'Back', polls_path %>

app/views/polls/index.html.erb
<!-- create a poll here -->
<%= render 'form' %>

<table>
<% @polls.each do |poll| %>
	<tr>
		<td><%= link_to poll.title, poll.encrypted_link %></td>
	</tr>
	
<% end %>
</table>

app/views/polls/show.html.erb
<h2><%= @poll.title %><h2><br/>
<h4><%= @poll.question %></h4><br/>

<%= render 'answers/form' %>
<%= link_to 'Create a Poll', root_url %><br/>
<%= link_to 'Edit Poll', edit_poll_path(@poll) %><br/>
<%= link_to 'Delete Poll', poll_path %><br/>
<%= link_to 'Back to Polls', polls_path %>

<%#= debug params %>